### ISSUE TITLE
Error when deleting Orion record that does not exist

### ISSUE THREAD

**Issue by smatterchew** [ashleyghooper/solarwinds_ansible#2]
When deleting a host record with `orion_node` that does not exist:

```
TASK [Delete a record from Orion] **********************************************
task path: /home/user/dev/scratch/orion.yml:12
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~user && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786 `" && echo ansible-tmp-1666636276.7511418-35595-143509165700786="` echo /home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786 `" ) && sleep 0'
Using module file /home/user/.ansible/collections/ansible_collections/anophelesgreyhoe/solarwinds/plugins/modules/orion_node.py
<localhost> PUT /home/user/.ansible/tmp/ansible-local-35583zm9j784u/tmpwdpavv4m TO /home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/ /home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py && sleep 0'
<localhost> EXEC /bin/sh -c '~/venv/ansible/bin/python /home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py", line 100, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_anophelesgreyhoe.solarwinds.orion_node_payload_zdoucxik/ansible_anophelesgreyhoe.solarwinds.orion_node_payload.zip/ansible_collections/anophelesgreyhoe/solarwinds/plugins/modules/orion_node.py", line 1006, in <module>
  File "/tmp/ansible_anophelesgreyhoe.solarwinds.orion_node_payload_zdoucxik/ansible_anophelesgreyhoe.solarwinds.orion_node_payload.zip/ansible_collections/anophelesgreyhoe/solarwinds/plugins/modules/orion_node.py", line 1002, in main
TypeError: exit_json() argument after ** must be a mapping, not NoneType
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1666636276.7511418-35595-143509165700786/AnsiballZ_orion_node.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_anophelesgreyhoe.solarwinds.orion_node_payload_zdoucxik/ansible_anophelesgreyhoe.solarwinds.orion_node_payload.zip/ansible_collections/anophelesgreyhoe/solarwinds/plugins/modules/orion_node.py\", line 1006, in <module>\n  File \"/tmp/ansible_anophelesgreyhoe.solarwinds.orion_node_payload_zdoucxik/ansible_anophelesgreyhoe.solarwinds.orion_node_payload.zip/ansible_collections/anophelesgreyhoe/solarwinds/plugins/modules/orion_node.py\", line 1002, in main\nTypeError: exit_json() argument after ** must be a mapping, not NoneType\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Here is the Ansible task:
```yaml
    - name: "Delete a record from Orion"
      delegate_to: localhost
      anophelesgreyhoe.solarwinds.orion_node:
        solarwinds_connection:
          hostname: "{{ survey_solarwinds_host }}"
          username: "{{ survey_username }}"
          password: "{{ survey_password }}"
        state: absent
        node_name: "{{ survey_orion_nodename }}"
        ip_address: "{{ survey_ipaddr }}"
      tags:
        - delete
```

I don't get an error with the same task when the Orion host record is present.

**Comment by smatterchew** [comment]
I can confirm this fixed my issue.  Thank you.

**Comment by ashleyghooper** [comment]
Thanks for this bug report @smatterchew. Keep them coming if you find any more issues! :)

**Comment by smatterchew** [comment]
Sure.  @ashleyghooper, are you interested in feature requests?

**Comment by ashleyghooper** [comment]
Yes, open to any input on future directions. Please feel free to log an issue.
